// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6RZYXSRITGD3Peyut9cKTCg8GWs_h8pU',
    appId: '1:250324051887:web:9835d2545fc3236185f15a',
    messagingSenderId: '250324051887',
    projectId: 'notesapp-dccdf',
    authDomain: 'notesapp-dccdf.firebaseapp.com',
    storageBucket: 'notesapp-dccdf.firebasestorage.app',
    measurementId: 'G-VTLW1YDY53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6G20x3klMQCrNY8tI2i9elOzrEo1ZCbI',
    appId: '1:250324051887:android:36f5298631f97f7085f15a',
    messagingSenderId: '250324051887',
    projectId: 'notesapp-dccdf',
    storageBucket: 'notesapp-dccdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtRF3ZW9NzzwPf6UcCXUC654jadZVNA-Q',
    appId: '1:250324051887:ios:6bdf6fb81c248ab285f15a',
    messagingSenderId: '250324051887',
    projectId: 'notesapp-dccdf',
    storageBucket: 'notesapp-dccdf.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtRF3ZW9NzzwPf6UcCXUC654jadZVNA-Q',
    appId: '1:250324051887:ios:6bdf6fb81c248ab285f15a',
    messagingSenderId: '250324051887',
    projectId: 'notesapp-dccdf',
    storageBucket: 'notesapp-dccdf.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6RZYXSRITGD3Peyut9cKTCg8GWs_h8pU',
    appId: '1:250324051887:web:7d2aa968d2ab732f85f15a',
    messagingSenderId: '250324051887',
    projectId: 'notesapp-dccdf',
    authDomain: 'notesapp-dccdf.firebaseapp.com',
    storageBucket: 'notesapp-dccdf.firebasestorage.app',
    measurementId: 'G-ST6R9SFE9K',
  );
}
